### ISSUE TITLE
could not load library "libstlport_shared.so" needed by "libJniBitmapOperationsLib.so"; caused by load_library(linker.cpp:769): too small to be an ELF executable: libstlport_shared.so

### ISSUE THREAD

**Issue by SZn007** [AndroidDeveloperLB/AndroidJniBitmapOperations#26]
load_library(linker.cpp:769): too small to be an ELF executable: libstlport_shared.so
E/linker: soinfo_link_image(linker.cpp:1647): could not load library "libstlport_shared.so" needed by "libJniBitmapOperationsLib.so"; caused by load_library(linker.cpp:769): too small to be an ELF executable: libstlport_shared.so
E/dalvikvm: dlopen("/data/app-lib/com.example.jnibitmapoperationstest-2/libJniBitmapOperationsLib.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1647): could not load library "libstlport_shared.so" needed by "libJniBitmapOperationsLib.so"; caused by load_library(linker.cpp:769): too small to be an ELF executable: libstlport_shared.so
E/AndroidRuntime: FATAL EXCEPTION: main java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1647): could not load library "libstlport_shared.so" needed by "libJniBitmapOperationsLib.so"; caused by load_library(linker.cpp:769): too small to be an ELF executable: libstlport_shared.so
                                                                                         at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                         at java.lang.System.loadLibrary(System.java:514)
                                                                                         at com.jni.bitmap_operations.JniBitmapHolder.<clinit>(JniBitmapHolder.java:13)
                                                                                         at com.example.jnibitmapoperationstest.MainActivity.<init>(MainActivity.java:25)
                                                                                         at java.lang.Class.newInstanceImpl(Native Method)
                                                                                         at java.lang.Class.newInstance(Class.java:1319)
                                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1054)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2260)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
                                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:162)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5371)
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                         at dalvik.system.NativeStart.main(Native Method)
12-07 10:59:26.527 529-547/? E/AppErrorDialog: Failed to get ILowStorageHandle instance
12-07 10:59:27.005 529-13755/? E/AEE/LIBAEE: shell: cant create socket with aed: Connection refused

**Comment by SZn007** [comment]
static {
    System.loadLibrary("stlport_shared");
    System.loadLibrary("JniBitmapOperationsLibrary");
}

**Comment by SZn007** [comment]
the apk crash on huawei Y511-T00  and with the code above the crash disappear

**Comment by AndroidDeveloperLB** [comment]
Sadly I've failed (multiple times) to import my own project, to Eclipse and to Android Studio.
What I suggest is to try out RenderScript for the same operations. Maybe it can help to perform the same things.

**Comment by AndroidDeveloperLB** [comment]
I've finally succeeded importing, and the project works fine. no idea why it won't work on some devices. can't confirm. 
i close this because i have no way to fix this.
